### ISSUE TITLE
checkpoint saving error

### ISSUE THREAD

**Issue by LEECHAN96** [Deep-Imaging-Group/Physics-Model-Data-Driven-Review#2]
Hello, when I finish training epoch 0, I encountered this error:

```
Traceback (most recent call last):
  File "E:\PycharmProjects\Physics-Model-Data-Driven-Review-main\demos\LPD.py", line 134, in <module>
    trainer.fit(network, train_loader, vali_loader)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 440, in fit
    results = self.accelerator_backend.train()
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\accelerators\gpu_accelerator.py", line 54, in train
    results = self.train_or_test()
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 483, in train
    self.train_loop.run_training_epoch()
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 562, in run_training_epoch
    self.trainer.run_evaluation(test_mode=False)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 610, in run_evaluation
    self.evaluation_loop.on_evaluation_end()
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 109, in on_evaluation_end
    self.trainer.call_hook('on_validation_end', *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 823, in call_hook
    trainer_hook(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\trainer\callback_hook.py", line 177, in on_validation_end
    callback.on_validation_end(self, self.get_model())
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 167, in on_validation_end
    self.save_checkpoint(trainer, pl_module)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 213, in save_checkpoint
    self._save_top_k_checkpoints(monitor_candidates, trainer, pl_module, epoch, filepath)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 494, in _save_top_k_checkpoints
    self._update_best_and_save(filepath, current, epoch, trainer, pl_module)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 543, in _update_best_and_save
    self._save_model(filepath, trainer, pl_module)
  File "C:\ProgramData\Anaconda3\envs\v102\lib\site-packages\pytorch_lightning\callbacks\model_checkpoint.py", line 297, in _save_model
    raise ValueError(".save_function() not set")
ValueError: .save_function() not set
Epoch 0: 100%|██████████| 350/350 [05:11<00:00,  1.12it/s, loss=0.002, v_num=1]
```

This seems to be about the saving of check-point. Are there any parameters I haven't set?
**LPD.py:**
```
if __name__ == "__main__":
    args = get_parameters()
    network = net(args)
    checkpoint_callback = ModelCheckpoint(monitor="val_loss", save_last=True, save_top_k=3, mode="min")
    trainer = pl.Trainer(gpus=args.gpu_ids if args.is_specified_gpus else args.gpus, log_every_n_steps=1, max_epochs=args.epochs, callbacks=[checkpoint_callback])
    train_loader = DataLoader(data_loader(args.data_root_dir, args.dose, 'train'), batch_size=args.batch_size, shuffle=True, num_workers=args.cpus)
    vali_loader = DataLoader(data_loader(args.data_root_dir, args.dose, 'vali'), batch_size=args.batch_size, shuffle=False, num_workers=args.cpus)
    test_loader = DataLoader(data_loader(args.data_root_dir, args.dose, 'test'), batch_size=args.batch_size, shuffle=False, num_workers=args.cpus)
    trainer.fit(network, train_loader, vali_loader)
    # trainer.fit(network, train_loader, vali_loader, ckpt_path='lightning_logs/version_0/checkpoints/last.ckpt')
    trainer.test(network, test_loader, ckpt_path='best')
```
**config.json:**
```
"data_root_dir": {
        "type": "str",
        "help": "Root dir of data",
        "default": "./dataset_review"},
"dose": {
        "type": "str",
        "help": "Dose of low-dose CT",
        "default": "20%"},
......
"is_res_save": {
        "type": "bool",
        "help": "Whether save the test res",
        "default": true},
"res_dir": {
        "type": "str",
        "help": "The dir to save the test res",
        "default": "./result"},
```

Thank you in advance!

**Comment by LEECHAN96** [comment]
It is fixed by upgrading my pytorch-lightning.
